### ISSUE TITLE
What to do when a drug has multiple targets?

### ISSUE THREAD

**Issue by napaintian** [ZJUFanLab/scRank#1]
Hello, I would like to ask you if a drug has multiple targets, how to write parameters to find the cell type on which the drug acts?

**Comment by Lee0498** [comment]
Hi @napaintian,

Thank you for reaching out and for your question!

When dealing with a drug that has multiple targets, you can specify the drug target genes with the parameter `perturbed_target` in function `rank_celltype()`. Here’s an example of what the parameters might look like:
```{R}
scRank_obj <- rank_celltype(object = scRank_obj, perturbed_target = c('MAP2K1',MAP2K2'))
```

**Comment by napaintian** [comment]
There are three target genes for my drug (hubgene). I will report an error after running with the code below. What's going on?
hubgene <- c("AKT1","EGFR","CASP3")
scRank <- CreateScRank(sce_obj,
                       cell_type = "cell_type_leiden0.5",
                       species = "human",target = hubgene
                       )
scRank <- scRank::Constr_net(scRank)
scRank <- scRank::rank_celltype(scRank,perturbed_target = hubgene)
Error in scRank::rank_celltype(scRank, perturbed_target = hubgene) : 
  The number of perturbed gene should not be more than two!

**Comment by Lee0498** [comment]
Dear napaintian,
Thank you for your interest in scRank. In its current version, scRank supports up to two target genes as input. This limitation is due to the inherent complexities of multi-target perturbation, such as modeling synergistic effects, which are challenging to accurately capture.
To proceed, we recommend prioritizing your gene list to select the top two targets with the most significant biological signals in your data (like variability).
